### ISSUE TITLE
Double-check French translation on terms pop-up

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hp-north-america#13]
We need to double-check the French translation of the terms pop-up in [https://github.com/gbif/hp-north-america/blob/master/_data/translations.yml](https://github.com/gbif/hp-north-america/blob/master/_data/translations.yml)

**Comment by jenningsdt** [comment]
Also double-check `other` in [https://github.com/gbif/hp-north-america/blob/master/_data/fr/footer.yml](https://github.com/gbif/hp-north-america/blob/master/_data/fr/footer.yml)

**Comment by CaroleSinou** [comment]
Both https://github.com/gbif/hp-north-america/blob/master/_data/translations.yml and https://github.com/gbif/hp-north-america/blob/master/_data/fr/footer.yml have been verified.
The privacy policy need to be translated.
