### ISSUE TITLE
How to steal picture overflowing the menu bar 

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-north-america#17]
Hi @albenson-usgs ,

I was looking at your portal and we liked the picture overflowing the menu bar and we want to try it out.

<img width="1387" alt="Captura de Pantalla 2022-07-19 a la(s) 11 07 39 a  m" src="https://user-images.githubusercontent.com/5700527/179797723-2a811042-b2c8-4f3c-bc4f-f2e5eeb055f8.png">

I search trou your .css and .js file and home files to 'steal' this design feature but I could find it, could you please point me to the code.

Thank you in advance,

**Comment by albenson-usgs** [comment]
@camiplata I don't remember how to do this which makes me think that it's something @MortenHofft did for us. He spruced it up a bit for us before it went live.

**Comment by albenson-usgs** [comment]
I'm thinking it might be the heroImage under the composition block [here](https://raw.githubusercontent.com/gbif/hp-bison/master/home.md).

**Comment by camiplata** [comment]
Thank you Abby!! was this piece of the front matter: 

navbar:
    color: transparent
    hasWhiteText: true
    floating: true

For the coming hosted portal maybe it will be nice to add some aditional documentation for this.

**Comment by MortenHofft** [comment]
For some reason I never linked to this example: https://hp-theme.gbif-staging.org/examples/transparent-header/
