### ISSUE TITLE
Desire click-through on news and events on home page

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hp-north-america#2]
On the home page, we are showing several news and event items. However, you cannot click-through to the content directly (i.e., you need to go to the News & Events page and click-through from that page). Is it possible to add click-through functionality from the home page?

**Comment by MortenHofft** [comment]
That is a bug. I'm closing this in favour of https://github.com/gbif/hosted-portals/issues/24

**Comment by MortenHofft** [comment]
I've verified that the issue has been resolved on the website
