### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hp-north-america#3]
It would be nice to enable Google Analytics for the hosted portal. I believe this is being discussed in the hosted-portals repository. Once the capability exists, we need to integrate the functionality into the North America Region portal. The data will help the steering group understand the usefulness of the portal.

**Comment by jenningsdt** [comment]
Note that this is related to https://github.com/gbif/hosted-portals/issues/16

**Comment by nielsraes** [comment]
Some user stats for the institutional portal of 'Het Natuurhistorisch' would be appreciated.

**Comment by jenningsdt** [comment]
I setup the Google ID using our gbif.na.helpdesk@gmail.com email address.

**Comment by jenningsdt** [comment]
Google Analytics is now enabled on the hosted portal.
