### ISSUE TITLE
Favicon for browser bar

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hp-north-america#4]
Consider adding the GBIF mark as the favicon for the North America Region page (e.g., similar to how it appears on https://www.gbif.org/). However, we will need some guidance for how to implement this on the hosted portal.

**Comment by MortenHofft** [comment]
In the simplest version you just add a `favicon.ico` to the root of the project. Then it should appear in tabs etc.

These days favicons are rocket science, so if you want to have control over how it appears if someone
* adds the website to the ios home screen on ios7 vs ios8
* high resolution screen or low resolution. 
* etc.

then you can go to e.g. https://realfavicongenerator.net/ or [another generator](https://www.google.com/search?q=favicon+generator) and have them generate a ton of files and some html code that you can insert in your project.
They will ask you to locate all files in the root of your project (it feels like littering, but that is the recommendation).

And then add a html snippet to your head. For our project that means creating a `_includes/favicon.html` file with the html. That will then be inserted in `<head>`. Something like

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

**Comment by jenningsdt** [comment]
Thanks! Can GBIF simply supply us with their official branded favicons since our portal represents one of the GBIF regions? (Similar to how we were provided with an official branded logo for our region - see https://github.com/gbif/hp-north-america/commit/d0e8b9fbcc1559af418bcddf784c627a57a5bb60 .) Although, it may be easier for me to go to gbif.org, view source, and then copy the head and icons from there.

**Comment by MortenHofft** [comment]
@kcopas are there any restrictions on this?
The link is here https://www.gbif.org/favicon.ico

**Comment by jenningsdt** [comment]
I spoke with @kcopas via the GBIF North America Slack workspace, and he said that the official branded GBIF favicons would be required for our portal since we are representing an official GBIF region. I will download the favicons and html from gbif.org and apply to our portal.
