### ISSUE TITLE
Danish translations

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hp-north-america#5]
The initial iterations of the Hosted Portals included Danish translations. Will these translations be updated or were they included only as examples? If the former, then what is the trigger for getting them updated (noting that we have more updates to make still)? If the latter, then I assume it is okay to delete Danish in an effort to clean up the file structures.

**Comment by MortenHofft** [comment]
Danish was just an example - I assumed it was so obscure that it wouldn't be considered giving preference to any specific language. You can just delete it. 

You might want to look at https://hp-theme.gbif-staging.org/translations

**Comment by MortenHofft** [comment]
https://github.com/gbif/hp-north-america/tree/master/_data/da
https://github.com/gbif/hp-north-america/tree/master/da
Remember to also delete https://github.com/gbif/hp-north-america/blob/master/_data/languages.yml#L10

**Comment by jenningsdt** [comment]
Completed removal of Danish elements.
